### PR TITLE
UPDATE SOLARNUANA FCL DEFAULTS

### PR DESCRIPTION
**Pull request by mantheys**

### CODE REVIEW

**Comment by aolivier23** [comment]
This needs an expert reviewer because it seems to change important analysis modules.

**Comment by aolivier23** [comment]
trigger build with DUNE/duneana#87

**Comment by mantheys** [comment]
Hi @aolivier23 happy to get input from other folks, but I'm the creator, writer, maintainer and (as far as I know) only user of the SolarNuAna and MCParticleAna modules.

**Comment by aolivier23** [comment]
Thank you for clarifying.  I'll try to merge this today.

**Comment by mantheys** [comment]
Sure! No hurry, thanks for reviewing.

**Review by aolivier23 — APPROVED** [review]
Code looks like it should compile and produce good physics.  I'll merge this as soon as CI confirms that it builds.

**Comment by aolivier23** [comment]
trigger build with DUNE/duneana#87

**Comment by aolivier23** [comment]
Not sure why CI is only building LArSoft.  Trying to get it to test this before I resort to doing it manually.  I'll get it done today either way.

**Pull request merged**
