### PR TITLE
update module to accept any gen input

### PR DESCRIPTION
**Pull request by mantheys**
The main change of this PR is to generalize the module to accept any list of generator labels coming from the _job.fcl and still return sensible output.

In the previous version, the generator labels (marley, bkg...) needed to match precisely the labels of the mctruth products in the art file. This is no longer needed. These changes were conceived to allow the analysis of marley mc productions with individual (or multiple but not all) bkg components.

These changes simplify the _job.fcl to only depend on the selected geometry (assuming standard bkg model).

### CODE REVIEW

**Comment by vhewes** [comment]
hi Sergio! i had a brief look thru the changes and i think they look essentially fine, but it would be good to get a brief summary in the body of the PR about the reason for the changes.

i see you removed a number of existing FCLs, updated a couple more, and made pretty significant changes to the solar neutrino analysis module – if you can just give a quick summary of the work you did in a couple of paragraphs, that would be amazing. thank you!

**Comment by vhewes** [comment]
hey Sergio! i took a look thru the module and i have a quick note on a better way to handle debug printouts. Art already has a service called `MessageFacility` for handling verbosity, that you might want to use instead of the current implementation.

as currently implemented, the analysis module has a bool `fDebug`

https://github.com/DUNE/duneana/blob/d09b22525c1a0b66f935645e09a29572c894f352/duneana/SolarNuAna/SolarNuAna_module.cc#L88

which corresponds to a FHICL parameter

https://github.com/DUNE/duneana/blob/d09b22525c1a0b66f935645e09a29572c894f352/duneana/SolarNuAna/SolarNuAna_module.cc#L148

that you then use to filter your `cout` statements. some of them are always enabled, such as

https://github.com/DUNE/duneana/blob/d09b22525c1a0b66f935645e09a29572c894f352/duneana/SolarNuAna/SolarNuAna_module.cc#L283-L288

while others can be enabled or disabled using the `Debug` parameter, such as

https://github.com/DUNE/duneana/blob/d09b22525c1a0b66f935645e09a29572c894f352/duneana/SolarNuAna/SolarNuAna_module.cc#L425-L427

technically speaking, there's nothing _incorrect_ about this approach – but there is a better way of handling the verbosity of your module!

`MessageFacility` is essentially an alternative to `cout` that lets the user set the verbosity level for each printed statement, and then configure Art's verbosity at a global scale at runtime via FHICL. it looks like it's already included at the top of the module:

https://github.com/DUNE/duneana/blob/b8c4cf870d8c7226736fe8603302065b170c4ae6/duneana/SolarNuAna/SolarNuAna_module.cc#L49

so it should already be available. for an example of usage, see this line from the `DAQSimAna` module:

https://github.com/DUNE/duneana/blob/b8c4cf870d8c7226736fe8603302065b170c4ae6/duneana/DAQSimAna/DAQSimAna_module.cc#L315

there are other various options such as `LogWarning`, `LogInfo` etc – you can see more information on the usage of `MessageFacility` at [this redmine wiki page](https://cdcvs.fnal.gov/redmine/projects/messagefacility/wiki/Log_messages). in an ideal world, a LArSoft module shouldn't use `cout` at all, and will just log everything thru the `MessageFacility`.

**Comment by mantheys** [comment]
I've updated the debug messages to work with the MessageLogger facility. There are still a few messages that print directly to the terminal, but those are actually relevant information for the time of running, such as #hits per plane, #clusters per plane, and #flashes as well as the summary information of the matched clusters that pass the preselection of the analysis. There is still some proprietary debug print in the CalcAdjHits function although that is hard coded to be off. I just didn't want to modify the function too much. That's part of the code that we have inherited from the DAQSimAna _module.

**Comment by vhewes** [comment]
thanks Sergio! this is looking good – to your question, if you look at the documentation i linked in the PR, you'll see that `mf::LogDebug` is not the only option – there are also other options like `mf::LogInfo`, `mf::LogError`, `mf::LogError`. these different levels are hierarchical, and depending on context, the user can choose how much information they want at runtime by setting a line in their job FHICL using something like 

```
services.message.destinations.LogStandardOut.threshold: "INFO"
```

which will silence any debug outputs, but will print any info, warning or error outputs. for a large-scale production job, where we might not want a huge spew of information outputs, we could turn the log threshold down to warning, silencing the debug and info outputs and only printing warnings or errors that could be the sign of a problem.

it sounds like the outputs you're describing could be `LogInfo` calls – that way, you can run with that level enabled to see that information, but if this module were to be run at scale as part of a major production, the production team could silence them simply by changing the log threshold, without needing to make any changes to your code.

let me know if that all makes sense! and thank you, this is looking really good 🙏

**Comment by tomjunk** [comment]
V and Sergio -- let us know when  you are happy with this PR and we can merge it.

**Pull request merged**
