### PR TITLE
Update to solarnuana

### PR DESCRIPTION
**Pull request by mantheys**
I include some new entries to the output tree and allow for further constraints in the ind/col plane matching part of the algorithm. This is expected to ensure a better vertex reconstruction by ensuring a better match between the clusters detected by each of the tpc planes.

### CODE REVIEW

**Review by Hamza-Amar — APPROVED** [review]
It seems to be fine.

**Comment by calcuttj** [comment]
This is causing failures in c7 builds. Please address

https://dbweb8.fnal.gov:8443/LarCI/app/ns:dune/storage/docs/2023/08/17/buildDUNE%232S2Wmud.log

**Comment by calcuttj** [comment]
Next time you can run CI tests for e20:prof and c7:prof by commenting "trigger build" (lowercase) on the PR

**Comment by mantheys** [comment]
Hi Jake! Thanks a lot for fixing the unused Run & SubRun variables. I see you have reformatted the code and fixed some wrong comments. Was there any other change needed? Should I test the code? Thanks again! Sorry about my late comments. I was on vacation this last weeks.

**Pull request merged**
