### PR TITLE
Feature/vpec calibanatree

### PR DESCRIPTION
**Pull request by vpec0**
This PR adds an analyser which creates a common ntuple for calibration analyses. The code was ported from SBNCode, originally developed by Gray Putnam.

We have implemented it as a single package under duneana and included the output object definition and ROOT dictionary (in contrast with the original SBN code where the analyser and the object definitions live in separate repositories).

The analyser processes each track according to a custom selection and stores relevant info - reco and MC truth - in the output ROOT TTree. The tree entries are track by track as opposed to more common event by event.

We have implemented/ported three selection tools: 
- select all tracks
- select anode-to-cathode crossers
- select stopping particles (muons)

The analyser can be configured to use any number of the selection tools where the selection is inclusive.

In addition, one can also specify a requirement that tracks have a T0 tag, this is an exclusive selection.

The code has been tested on a ProtoDUNE HD MC sample.

Default configurations may need some tuning.

### CODE REVIEW

**Comment by vpec0** [comment]
I would like to polish the default configurations in duneana/duneana/CalibAna/fcl/dune_calibanatree.fcl. Namely to provide defaults for running on different data samples, eg. FD HD/VD, ProtoDUNE HD/VD data vs MC.

As a first step, I would like to have the proper producer labels for the input products for ProtoDUNE HD MC.

Also, configuration to use Gnocchi calorimetry algorithm needs to be added.

**Comment by calcuttj** [comment]
Got this to build. Gonna finish testing later/tomorrow

**Comment by calcuttj** [comment]
trigger build with #64

**Comment by calcuttj** [comment]
trigger build with #64 dunecore/#112

**Comment by calcuttj** [comment]
trigger build with #64 DUNE/dunecore#64

**Comment by calcuttj** [comment]
trigger build with #64 DUNE/dunecore#112

**Review by calcuttj — APPROVED** [review]

**Pull request merged**
