### PR TITLE
add LowEnergy Cluster analysis in CalibAnaTree 

### PR DESCRIPTION
**Pull request by emilelavaut**
I change hit.ROISummedADC by hit.Integral because of the issues of compatibility with data/mc files reconstructed before the change SUmmedADC -> ROISummedADC. These files does not possess this method but you need to use this method if you want your code to compile. So to pursue my analysis on energy I use Integral which is less precise but present in both versions

### CODE REVIEW

**Comment by aolivier23** [comment]
I want someone more familiar with this code to review it before I approve.  I want to make sure we're not taking things out of the calibration analysis that other people are relying on.  I'll merge it today if you can get it approved by someone by say 1PM Chicago time.

**Review by vpec0 — CHANGES_REQUESTED** [review]
I don’t recommend merging the code in this state. The analyzer tool is relatively simple tool and complex code with ambitions comparable to event reconstruction should be included as specialized tools in separate libraries.
Also, configuration, especially being this complex for the clustering part, should also be separated from the track oriented part.

**Review by matt-siden — APPROVED** [review]
Verified the proposed changes to the analyzer do not impact existing workflows.

**Comment by aolivier23** [comment]
trigger build with DUNE/dunesw#82

**Comment by aolivier23** [comment]
trigger build with DUNE/duneana#82

**Comment by aolivier23** [comment]
Looks like I can fix the remaining Clang error.  I'll merge this and make a commit to fix it.

**Pull request merged**
